apiVersion: v1
kind: Service
metadata:
  name: {{ include "dog-facts-service.fullname" . }}
  labels:
    {{- include "dog-facts-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "dog-facts-service.selectorLabels" . | nindent 4 }}
